
"use client";

import { useState, useEffect } from 'react';
import type { FileContent } from '@/lib/types';
import { summarizeFile } from '@/ai/flows/summarize-file';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Loader } from 'lucide-react';

export function SummaryViewer({ fileContent }: { fileContent: FileContent }) {
    const [summary, setSummary] = useState<string | null>(null);
    const [isLoading, setIsLoading] = useState<boolean>(true);

    useEffect(() => {
        const getSummary = async () => {
            if (!fileContent.rawMetadata) {
                setSummary("No metadata available to generate a summary.");
                setIsLoading(false);
                return;
            }
            setIsLoading(true);
            try {
                // Use rawMetadata for summary if available, otherwise use content.
                const contentToSummarize = fileContent.rawMetadata;
                const result = await summarizeFile({
                    fileContent: contentToSummarize,
                    filename: fileContent.name,
                });
                setSummary(result.summary);
            } catch (error) {
                console.error("Failed to generate summary:", error);
                setSummary("Could not generate a summary for this file.");
            } finally {
                setIsLoading(false);
            }
        };

        getSummary();
    }, [fileContent]);

    return (
        <Card className="h-full">
            <CardHeader>
                <CardTitle>AI-Generated Summary</CardTitle>
                <CardDescription>A concise overview of the file's contents, generated by AI.</CardDescription>
            </CardHeader>
            <CardContent>
                {isLoading ? (
                    <div className="flex items-center gap-2 text-muted-foreground">
                        <Loader className="w-4 h-4 animate-spin" />
                        <span>Generating summary...</span>
                    </div>
                ) : (
                    <p className="whitespace-pre-wrap">{summary}</p>
                )}
            </CardContent>
        </Card>
    );
}
